dubbo:
  application:
    name: ego-manage
  registry:
    address: zookeeper://192.168.1.128:2181
server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons
